name: al_bayan_quran
description: "All in one Al Quran App with Translation, Tefsir, Quran Audiobook & Notes Backup"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.13.4+28

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  appwrite: ^12.0.1
  flutter_widget_from_html_core: ^0.15.1
  archive: ^3.4.10
  google_fonts: ^6.1.0
  url_launcher: ^6.2.6
  es_compression: ^2.0.11
  flutter_launcher_icons: ^0.13.1
  connectivity_plus: ^6.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.0.0
  get: ^5.0.0-release-candidate-6
  email_validator: ^3.0.0
  clipboard: ^0.1.3
  dart_appwrite: ^11.0.2
  just_audio: ^0.9.36
  just_audio_mpv: ^0.1.7
  salomon_bottom_bar: ^3.3.2
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.4
  regexpattern: ^2.6.0
  sidebarx: ^0.17.1
  flutter_localizations:
    sdk: flutter
  gap: ^3.0.1
  fluentui_system_icons: ^1.1.249
  simple_icons: ^10.1.3
  dio: ^5.4.3+1
  path_provider: ^2.1.3
  path: ^1.9.0

  # google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  msix: ^3.16.7

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/makkah.jpg
    - assets/img/madina.jpeg
    - assets/img/QuranLogo.jpg

 
  # fonts:
  #   - family: Majeed-Quranic
  #     fonts:
  #       - asset: assets/fonts/Al Qalam Quran.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/QuranLogo.jpg"
  web:
    generate: true
    image_path: "assets/img/QuranLogo.jpg"
    background_color: "#000000"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "assets/img/QuranLogo.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/img/QuranLogo.jpg"