List<Map<String, dynamic>> allTafseer = [
  {
    "author_name": "AbdulRahman Bin Hasan Al-Alshaikh",
    "id": 381,
    "language_name": "bengali",
    "name": "Tafsir Fathul Majid",
    "slug": "tafisr-fathul-majid-bn",
  },
  {
    "author_name": "Hafiz Ibn Kathir",
    "id": 169,
    "name": "Tafsir Ibn Kathir (abridged)",
    "language_name": "english",
    "slug": "en-tafisr-ibn-kathir",
  },
  {
    "author_name": "Hafiz Ibn Kathir",
    "id": 14,
    "language_name": "arabic",
    "name": "Tafsir Ibn Kathir",
    "slug": "ar-tafsir-ibn-kathir",
  },
  {
    "author_name": "Tawheed Publication",
    "id": 164,
    "language_name": "bengali",
    "name": "Tafseer ibn Kathir",
    "slug": "bn-tafseer-ibn-e-kaseer",
  },
  {
    "author_name": "Bayaan Foundation",
    "id": 165,
    "language_name": "bengali",
    "name": "Tafsir Ahsanul Bayaan",
    "slug": "bn-tafsir-ahsanul-bayaan",
  },
  {
    "author_name": "King Fahd Quran Printing Complex",
    "id": 166,
    "language_name": "bengali",
    "name": "Tafsir Abu Bakr Zakaria",
    "slug": "bn-tafsir-abu-bakr-zakaria",
  },
  {
    "author_name": "Mufti Muhammad Shafi",
    "id": 168,
    "language_name": "english",
    "name": "Maarif-ul-Quran",
    "slug": "en-tafsir-maarif-ul-quran",
  },
  {
    "author_name": "Saddi",
    "id": 170,
    "language_name": "russian",
    "name": "Tafseer Al Saddi",
    "slug": "ru-tafseer-al-saddi",
  },
  {
    "author_name": "Saddi",
    "id": 91,
    "language_name": "arabic",
    "name": "Tafseer Al Saddi",
    "slug": "ar-tafseer-al-saddi",
  },
  {
    "author_name": "Baghawy",
    "id": 94,
    "language_name": "arabic",
    "name": "Tafseer Al-Baghawi",
    "slug": "ar-tafsir-al-baghawi",
  },
  {
    "author_name": "Tanweer",
    "id": 92,
    "language_name": "arabic",
    "name": "Tafseer Tanwir al-Miqbas",
    "slug": "ar-tafseer-tanwir-al-miqbas",
  },
  {
    "author_name": "Waseet",
    "id": 93,
    "language_name": "arabic",
    "name": "Tafsir Al Wasit",
    "slug": "ar-tafsir-al-wasit",
  },
  {
    "author_name": "Tabari",
    "id": 15,
    "language_name": "arabic",
    "name": "Tafsir al-Tabari",
    "slug": "ar-tafsir-al-tabari",
  },
  {
    "author_name": "\u0627\u0644\u0645\u06cc\u0633\u0631",
    "id": 16,
    "language_name": "arabic",
    "name": "Tafsir Muyassar",
    "slug": "ar-tafsir-muyassar",
  },
  {
    "author_name": "Qurtubi",
    "id": 90,
    "language_name": "arabic",
    "name": "Tafseer Al Qurtubi",
    "slug": "ar-tafseer-al-qurtubi",
  },
  {
    "author_name": "Rebar Kurdish Tafsir",
    "id": 804,
    "language_name": "Kurdish",
    "name": "Rebar Kurdish Tafsir",
    "slug": "kurd-tafsir-rebar",
  },
  {
    "author_name": "Sayyid Ibrahim Qutb",
    "id": 157,
    "language_name": "urdu",
    "name": "Fi Zilal al-Quran",
    "slug": "tafsir-fe-zalul-quran-syed-qatab",
  },
  {
    "author_name": "Hafiz Ibn Kathir",
    "id": 160,
    "language_name": "urdu",
    "name": "Tafsir Ibn Kathir",
    "slug": "tafseer-ibn-e-kaseer-urdu",
  },
  {
    "author_name": "Dr. Israr Ahmad",
    "id": 159,
    "language_name": "urdu",
    "name": "Tafsir Bayan ul Quran",
    "slug": "tafsir-bayan-ul-quran",
  }
];
List<Map<String, dynamic>> allLanguages = [
  {
    "id": 38,
    "name": "English",
    "iso_code": "en",
    "d": "English",
    "direction": "ltr",
    "translations_count": 19,
  },
  {
    "id": 174,
    "name": "Urdu",
    "iso_code": "ur",
    "d": "اردو",
    "direction": "rtl",
    "translations_count": 9,
  },
  {
    "id": 20,
    "name": "Bengali",
    "iso_code": "bn",
    "d": "বাংলা",
    "direction": "ltr",
    "translations_count": 7,
  },
  {
    "id": 167,
    "name": "Turkish",
    "iso_code": "tr",
    "d": "Türkçe",
    "direction": "ltr",
    "translations_count": 6,
  },
  {
    "id": 40,
    "name": "Spanish",
    "iso_code": "es",
    "d": "Español",
    "direction": "ltr",
    "translations_count": 5,
  },
  {
    "id": 23,
    "name": "Bosnian",
    "iso_code": "bs",
    "d": "Bosanski",
    "direction": "ltr",
    "translations_count": 4,
  },
  {
    "id": 49,
    "name": "French",
    "iso_code": "fr",
    "d": "Français",
    "direction": "ltr",
    "translations_count": 4,
  },
  {
    "id": 106,
    "name": "Malayalam",
    "iso_code": "ml",
    "d": "മലയാളം",
    "direction": "ltr",
    "translations_count": 4,
  },
  {
    "id": 138,
    "name": "Russian",
    "iso_code": "ru",
    "d": "Русский",
    "direction": "ltr",
    "translations_count": 4,
  },
  {
    "id": 118,
    "name": "Dutch",
    "iso_code": "nl",
    "d": "Nederlands",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 67,
    "name": "Indonesian",
    "iso_code": "id",
    "d": "Bahasa Indonesia",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 74,
    "name": "Italian",
    "iso_code": "it",
    "d": "Italiano",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 76,
    "name": "Japanese",
    "iso_code": "ja",
    "d": "日本語",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 160,
    "name": "Tajik",
    "iso_code": "tg",
    "d": "",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 175,
    "name": "Uzbek",
    "iso_code": "uz",
    "d": "",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 177,
    "name": "Vietnamese",
    "iso_code": "vi",
    "d": "Tiếng Việt",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 185,
    "name": "Chinese",
    "iso_code": "zh",
    "d": "中文",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 187,
    "name": "Albanian",
    "iso_code": "sq",
    "d": "Shqip",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 33,
    "name": "German",
    "iso_code": "de",
    "d": "Deutsch",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 158,
    "name": "Tamil",
    "iso_code": "ta",
    "d": "தமிழ்",
    "direction": "ltr",
    "translations_count": 3,
  },
  {
    "id": 82,
    "name": "Kazakh",
    "iso_code": "kk",
    "d": "Қазақ",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 84,
    "name": "Central Khmer",
    "iso_code": "km",
    "d": "",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 10,
    "name": "Assamese",
    "iso_code": "as",
    "d": "অসমীয়া",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 133,
    "name": "Portuguese",
    "iso_code": "pt",
    "d": "Português",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 19,
    "name": "Bambara",
    "iso_code": "bm",
    "d": "",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 34,
    "name": "Divehi, Dhivehi, Maldivian",
    "iso_code": "dv",
    "d": "ދިވެހި",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 16,
    "name": "Bulgarian",
    "iso_code": "bg",
    "d": "Български",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 110,
    "name": "Malay",
    "iso_code": "ms",
    "d": "Bahasa Melayu",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 150,
    "name": "Somali",
    "iso_code": "so",
    "d": "",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 60,
    "name": "Hindi",
    "iso_code": "hi",
    "d": "हिन्दी",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 86,
    "name": "Korean",
    "iso_code": "ko",
    "d": "한국어",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 89,
    "name": "Kurdish",
    "iso_code": "ku",
    "d": "Kurdî",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 13,
    "name": "Azeri",
    "iso_code": "az",
    "d": "Azərbaycan dili",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 157,
    "name": "Swahili",
    "iso_code": "sw",
    "d": "Kiswahili",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 58,
    "name": "Hausa",
    "iso_code": "ha",
    "d": "",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 43,
    "name": "Persian",
    "iso_code": "fa",
    "d": "فارسی",
    "direction": "rtl",
    "translations_count": 2,
  },
  {
    "id": 161,
    "name": "Thai",
    "iso_code": "th",
    "d": "ภาษาไทย",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 164,
    "name": "Tagalog",
    "iso_code": "tl",
    "d": "",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 137,
    "name": "Romanian",
    "iso_code": "ro",
    "d": "Română",
    "direction": "ltr",
    "translations_count": 2,
  },
  {
    "id": 190,
    "name": "Dari",
    "iso_code": "prs",
    "d": "دری",
    "direction": "rtl",
    "translations_count": 1,
  },
  {
    "id": 188,
    "name": "Amazigh",
    "iso_code": "zgh",
    "d": "Tamaziɣt",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 6,
    "name": "Amharic",
    "iso_code": "am",
    "d": "",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 25,
    "name": "Chechen",
    "iso_code": "ce",
    "d": "",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 29,
    "name": "Czech",
    "iso_code": "cs",
    "d": "Čeština",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 45,
    "name": "Finnish",
    "iso_code": "fi",
    "d": "Suomi",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 56,
    "name": "Gujarati",
    "iso_code": "gu",
    "d": "ગુજરાતી",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 59,
    "name": "Hebrew",
    "iso_code": "he",
    "d": "עברית",
    "direction": "rtl",
    "translations_count": 1,
  },
  {
    "id": 78,
    "name": "Georgian",
    "iso_code": "ka",
    "d": "ქართული",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 85,
    "name": "Kannada",
    "iso_code": "kn",
    "d": "",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 95,
    "name": "Ganda",
    "iso_code": "lg",
    "d": "",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 105,
    "name": "Macedonian",
    "iso_code": "mk",
    "d": "Македонски",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 108,
    "name": "Marathi",
    "iso_code": "mr",
    "d": "मराठी",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 109,
    "name": "Maranao",
    "iso_code": "mrn",
    "d": "",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 116,
    "name": "Nepali",
    "iso_code": "ne",
    "d": "नेपाली",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 120,
    "name": "Norwegian",
    "iso_code": "no",
    "d": "Norsk",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 126,
    "name": "Oromo",
    "iso_code": "om",
    "d": "",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 131,
    "name": "Polish",
    "iso_code": "pl",
    "d": "Polski",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 132,
    "name": "Pashto",
    "iso_code": "ps",
    "d": "پښتو",
    "direction": "rtl",
    "translations_count": 1,
  },
  {
    "id": 139,
    "name": "Kinyarwanda",
    "iso_code": "rw",
    "d": "Ikinyarwanda",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 142,
    "name": "Sindhi",
    "iso_code": "sd",
    "d": "",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 143,
    "name": "Northern Sami",
    "iso_code": "se",
    "d": "",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 145,
    "name": "Sinhala, Sinhalese",
    "iso_code": "si",
    "d": "සිංහල",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 152,
    "name": "Serbian",
    "iso_code": "sr",
    "d": "Српски",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 156,
    "name": "Swedish",
    "iso_code": "sv",
    "d": "Svenska",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 159,
    "name": "Telugu",
    "iso_code": "te",
    "d": "తెలుగు",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 169,
    "name": "Tatar",
    "iso_code": "tt",
    "d": "",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 172,
    "name": "Uighur, Uyghur",
    "iso_code": "ug",
    "d": "",
    "direction": "rtl",
    "translations_count": 1,
  },
  {
    "id": 173,
    "name": "Ukrainian",
    "iso_code": "uk",
    "d": "Українська",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 151,
    "name": "Albanian",
    "iso_code": "sq",
    "d": "Shqip",
    "direction": "ltr",
    "translations_count": 1,
  },
  {
    "id": 183,
    "name": "Yoruba",
    "iso_code": "yo",
    "d": "",
    "direction": "ltr",
    "translations_count": 1,
  }
];

List<Map<String, dynamic>> allTranslationLanguage = [
  {
    "id": 85,
    "name": "M.A.S. Abdel Haleem",
    "author_name": "Abdul Haleem",
    "slug": "en-haleem",
    "language_name": "english",
  },
  {
    "id": 131,
    "name": "Dr. Mustafa Khattab, The Clear Quran",
    "author_name": "Dr. Mustafa Khattab",
    "slug": "clearquran-with-tafsir",
    "language_name": "english",
  },
  {
    "id": 84,
    "name": "T. Usmani",
    "author_name": "Mufti Taqi Usmani",
    "slug": "en-taqi-usmani",
    "language_name": "english",
  },
  {
    "id": 95,
    "name": "A. Maududi (Tafhim commentary)",
    "author_name": "Sayyid Abul Ala Maududi",
    "slug": "en-al-maududi",
    "language_name": "english",
  },
  {
    "id": 79,
    "name": "Abu Adel",
    "author_name": "Abu Adel",
    "slug": "ru-abu-adel",
    "language_name": "russian",
  },
  {
    "id": 86,
    "name": "Office of the president of Maldives",
    "author_name": "Office of the president of Maldives",
    "slug": "dv-unknow",
    "language_name": "divehi, dhivehi, maldivian",
  },
  {
    "id": 19,
    "name": "M. Pickthall",
    "author_name": "Mohammed Marmaduke William Pickthall",
    "slug": "quran.en.pickthall",
    "language_name": "english",
  },
  {
    "id": 75,
    "name": "Alikhan Musayev",
    "author_name": "Alikhan Musayev",
    "slug": "az-alikhan",
    "language_name": "azeri",
  },
  {
    "id": 76,
    "name": "Muhammad Saleh",
    "author_name": "Muhammad Saleh",
    "slug": "ug-saleh",
    "language_name": "uighur, uyghur",
  },
  {
    "id": 83,
    "name": "Sheikh Isa Garcia",
    "author_name": "Sheikh Isa Garcia",
    "slug": "es-isa-garcia",
    "language_name": "spanish",
  },
  {
    "id": 78,
    "name": "Ministry of Awqaf, Egypt",
    "author_name": "Ministry of Awqaf, Egypt",
    "slug": "ru-ministry-of-awqaf",
    "language_name": "russian",
  },
  {
    "id": 81,
    "name": "Burhan Muhammad-Amin",
    "author_name": "Burhan Muhammad-Amin",
    "slug": "ku-burhan-muhammad",
    "language_name": "kurdish",
  },
  {
    "id": 80,
    "name": "Muhammad Karakunnu and Vanidas Elayavoor",
    "author_name": "Muhammad Karakunnu and Vanidas Elayavoor",
    "slug": "ml-karakunnu",
    "language_name": "malayalam",
  },
  {
    "id": 22,
    "name": "A. Yusuf Ali",
    "author_name": "Abdullah Yusuf Ali",
    "slug": "quran.en.yusufali",
    "language_name": "english",
  },
  {
    "id": 20,
    "name": "Saheeh International",
    "author_name": "Saheeh International",
    "slug": "en-sahih-international",
    "language_name": "english",
  },
  {
    "id": 203,
    "name": "Al-Hilali & Khan",
    "author_name": "Muhammad Taqi-ud-Din al-Hilali & Muhammad Muhsin Khan",
    "slug": "",
    "language_name": "english",
  },
  {
    "id": 234,
    "name": "Fatah Muhammad Jalandhari",
    "author_name": "Fatah Muhammad Jalandhari",
    "slug": "ur-fatah-muhammad-jalandhari",
    "language_name": "urdu",
  },
  {
    "id": 57,
    "name": "Transliteration",
    "author_name": "Transliteration",
    "slug": "transliteration",
    "language_name": "english",
  },
  {
    "id": 54,
    "name": "Maulana Muhammad Junagarhi",
    "author_name": "Maulana Muhammad Junagarhi",
    "slug": "ur-junagarri",
    "language_name": "urdu",
  },
  {
    "id": 156,
    "name": "Fe Zilal al-Qur'an",
    "author_name": "Sayyid Ibrahim Qutb",
    "slug": "urdu-sayyid-qatab",
    "language_name": "urdu",
  },
  {
    "id": 151,
    "name": "Shaykh al-Hind Mahmud al-Hasan(with Tafsir E Usmani)",
    "author_name": "Shaykh al-Hind Mahmud al-Hasan",
    "slug": "tafsir-e-usmani",
    "language_name": "urdu",
  },
  {
    "id": 158,
    "name": "Bayan-ul-Quran",
    "author_name": "Dr. Israr Ahmad",
    "slug": "bayan-ul-quran",
    "language_name": "urdu",
  },
  {
    "id": 97,
    "name": "Tafheem e Qur'an - Syed Abu Ali Maududi",
    "author_name": "Syed Abu Ali Maududi",
    "slug": "ur-al-maududi",
    "language_name": "urdu",
  },
  {
    "id": 136,
    "name": "Montada Islamic Foundation",
    "author_name": "Montada Islamic Foundation",
    "slug": null,
    "language_name": "french",
  },
  {
    "id": 135,
    "name": "IslamHouse.com",
    "author_name": "IslamHouse.com",
    "slug": null,
    "language_name": "persian",
  },
  {
    "id": 139,
    "name": "Khawaja Mirof & Khawaja Mir",
    "author_name": "Khawaja Mirof & Khawaja Mir",
    "slug": null,
    "language_name": "tajik",
  },
  {
    "id": 35,
    "name": "Ryoichi Mita",
    "author_name": "Ryoichi Mita",
    "slug": "ja-ryoichi-mita",
    "language_name": "japanese",
  },
  {
    "id": 134,
    "name": "King Fahad Quran Complex",
    "author_name": "King Fahad Quran Complex",
    "slug": null,
    "language_name": "indonesian",
  },
  {
    "id": 153,
    "name": "Hamza Roberto Piccardo",
    "author_name": "Hamza Roberto Piccardo",
    "slug": "hamza-roberto-piccardo",
    "language_name": "italian",
  },
  {
    "id": 161,
    "name": "Taisirul Quran",
    "author_name": "Tawheed Publication",
    "slug": "bn-taisirul-quran",
    "language_name": "bengali",
  },
  {
    "id": 163,
    "name": "Sheikh Mujibur Rahman",
    "author_name": "Darussalaam Publication",
    "slug": "bn-sheikh-mujibur-rahman",
    "language_name": "bengali",
  },
  {
    "id": 162,
    "name": "Rawai Al-bayan",
    "author_name": "Bayaan Foundation",
    "slug": "bn-rawai-al-bayan",
    "language_name": "bengali",
  },
  {
    "id": 210,
    "name": "Dar Al-Salam Center",
    "author_name": "Dar Al-Salam Center",
    "slug": null,
    "language_name": "turkish",
  },
  {
    "id": 211,
    "name": "Dar Al-Salam Center",
    "author_name": "Dar Al-Salam Center",
    "slug": null,
    "language_name": "tagalog",
  },
  {
    "id": 217,
    "name": "Dr. Mikhailo Yaqubovic",
    "author_name": "Dr. Mikhailo Yaqubovic",
    "slug": null,
    "language_name": "ukrainian",
  },
  {
    "id": 229,
    "name": "Sheikh Omar Sharif bin Abdul Salam",
    "author_name": "Sheikh Omar Sharif bin Abdul Salam",
    "slug": null,
    "language_name": "tamil",
  },
  {
    "id": 55,
    "name": "Muhammad Sodiq Muhammad Yusuf (Latin) ",
    "author_name": "Muhammad Sodiq Muhammad Yusuf",
    "slug": "quran.uz.sodik",
    "language_name": "uzbek",
  },
  {
    "id": 143,
    "name": "Muhammad Saleh Bamoki",
    "author_name": "Muhammad Saleh Bamoki",
    "slug": null,
    "language_name": "kurdish",
  },
  {
    "id": 141,
    "name": "The Sabiq company",
    "author_name": "The Sabiq company",
    "slug": "",
    "language_name": "indonesian",
  },
  {
    "id": 140,
    "name": "Montada Islamic Foundation",
    "author_name": "Montada Islamic Foundation",
    "slug": null,
    "language_name": "spanish",
  },
  {
    "id": 214,
    "name": "Dar Al-Salam Center",
    "author_name": "Dar Al-Salam Center",
    "slug": null,
    "language_name": "bosnian",
  },
  {
    "id": 227,
    "name": "Maulana Abder-Rahim ibn Muhammad",
    "author_name": "Maulana Abder-Rahim ibn Muhammad",
    "slug": null,
    "language_name": "telugu",
  },
  {
    "id": 226,
    "name": "Muhammad Shafi’i Ansari",
    "author_name": "Muhammad Shafi’i Ansari",
    "slug": null,
    "language_name": "marathi",
  },
  {
    "id": 233,
    "name": "Dar Al-Salam Center",
    "author_name": "Dar Al-Salam Center",
    "slug": null,
    "language_name": "hebrew",
  },
  {
    "id": 225,
    "name": "Rabila Al-Umry",
    "author_name": "Rabila Al-Umry",
    "slug": null,
    "language_name": "gujarati",
  },
  {
    "id": 224,
    "name": "Abdul-Hamid Haidar & Kanhi Muhammad",
    "author_name": "Abdul-Hamid Haidar & Kanhi Muhammad",
    "slug": null,
    "language_name": "malayalam",
  },
  {
    "id": 235,
    "name": "Malak Faris Abdalsalaam",
    "author_name": "Malak Faris Abdalsalaam",
    "slug": "nl-abdalsalaam",
    "language_name": "dutch",
  },
  {
    "id": 232,
    "name": "African Development Foundation",
    "author_name": "African Development Foundation",
    "slug": null,
    "language_name": "ganda",
  },
  {
    "id": 231,
    "name": "Dr. Abdullah Muhammad Abu Bakr and Sheikh Nasir Khamis",
    "author_name": "Dr. Abdullah Muhammad Abu Bakr and Sheikh Nasir Khamis",
    "slug": null,
    "language_name": "swahili",
  },
  {
    "id": 230,
    "name": "Society of Institutes and Universities",
    "author_name": "Society of Institutes and Universities",
    "slug": "",
    "language_name": "thai",
  },
  {
    "id": 223,
    "name": "Pioneers of Translation Center",
    "author_name": "Pioneers of Translation Center",
    "slug": null,
    "language_name": "tajik",
  },
  {
    "id": 222,
    "name": "Khalifa Altay",
    "author_name": "Khalifa Altay",
    "slug": null,
    "language_name": "kazakh",
  },
  {
    "id": 220,
    "name": "Ruwwad Center",
    "author_name": "Translation Pioneers Center",
    "slug": null,
    "language_name": "vietnamese",
  },
  {
    "id": 144,
    "name": "Sofian S. Siregar",
    "author_name": "Sofian S. Siregar",
    "slug": "nl_sofian_s._siregar",
    "language_name": "Dutch",
  },
  {
    "id": 88,
    "name": "Hasan Efendi Nahi",
    "author_name": "Hasan Efendi Nahi",
    "slug": "al-hasan-efendi",
    "language_name": "albanian",
  },
  {
    "id": 87,
    "name": "Sadiq and Sani",
    "author_name": "Sadiq and Sani",
    "slug": "am-sadiq",
    "language_name": "amharic",
  },
  {
    "id": 50,
    "name": "Jan Trust Foundation",
    "author_name": "Jan Trust Foundation",
    "slug": "ta-jan-trust",
    "language_name": "tamil",
  },
  {
    "id": 49,
    "name": "Ali Muhsin Al-Barwani",
    "author_name": "Ali Muhsin Al-Barwani",
    "slug": "sw-ali-muhsin",
    "language_name": "swahili",
  },
  {
    "id": 48,
    "name": "Knut Bernström",
    "author_name": "Knut Bernström",
    "slug": "sv-knut",
    "language_name": "swedish",
  },
  {
    "id": 128,
    "name": "Cambodian Muslim Community Development",
    "author_name": "Cambodian Muslim Community Development",
    "slug": null,
    "language_name": "central khmer",
  },
  {
    "id": 45,
    "name": "Russian Translation ( Elmir Kuliev )",
    "author_name": "Elmir Kuliev",
    "slug": "quran.ru.kuliev",
    "language_name": "russian",
  },
  {
    "id": 77,
    "name": "Turkish Translation(Diyanet)",
    "author_name": "Diyanet Isleri",
    "slug": "quran.tr.diyanet",
    "language_name": "turkish",
  },
  {
    "id": 39,
    "name": "Abdullah Muhammad Basmeih",
    "author_name": "Abdullah Muhammad Basmeih",
    "slug": "ms-abdullah",
    "language_name": "malay",
  },
  {
    "id": 36,
    "name": "Korean",
    "author_name": "Korean",
    "slug": "ko-unknown",
    "language_name": "korean",
  },
  {
    "id": 30,
    "name": "Finnish",
    "author_name": "Finnish",
    "slug": "fi-unknown",
    "language_name": "finnish",
  },
  {
    "id": 26,
    "name": "Czech",
    "author_name": "Czech",
    "slug": "cs-unknown",
    "language_name": "czech",
  },
  {
    "id": 103,
    "name": "Helmi Nasr",
    "author_name": "Helmi Nasr",
    "slug": null,
    "language_name": "portuguese",
  },
  {
    "id": 74,
    "name": "Tajik",
    "author_name": "AbdolMohammad Ayati",
    "slug": "tg-ayati",
    "language_name": "tajik",
  },
  {
    "id": 23,
    "name": "Azerbaijani",
    "author_name": "Azerbaijani",
    "slug": "az-unknown",
    "language_name": "azeri",
  },
  {
    "id": 101,
    "name": "Alauddin Mansour",
    "author_name": "Alauddin Mansour",
    "slug": null,
    "language_name": "uzbek",
  },
  {
    "id": 53,
    "name": "Tatar",
    "author_name": "Tatar",
    "slug": "tt-unknow",
    "language_name": "tatar",
  },
  {
    "id": 47,
    "name": "Albanian",
    "author_name": "Albanian",
    "slug": "sq-unknown",
    "language_name": "albanian",
  },
  {
    "id": 44,
    "name": "Grigore",
    "author_name": "George Grigore",
    "slug": "ro-grigore",
    "language_name": "Romanian",
  },
  {
    "id": 42,
    "name": "Józef Bielawski",
    "author_name": "Józef Bielawski",
    "slug": "pl-jozef-bielawski",
    "language_name": "polish",
  },
  {
    "id": 41,
    "name": "Norwegian",
    "author_name": "Norwegian",
    "slug": "no-unknown",
    "language_name": "norwegian",
  },
  {
    "id": 106,
    "name": "Magomed Magomedov",
    "author_name": "Magomed Magomedov",
    "slug": "chechen-translation",
    "language_name": "chechen",
  },
  {
    "id": 236,
    "name": "Ramdane At Mansour",
    "author_name": "Ramdane At Mansour",
    "slug": null,
    "language_name": "Amazigh",
  },
  {
    "id": 237,
    "name": "Tzvetan Theophanov",
    "author_name": "Tzvetan Theophanov",
    "slug": null,
    "language_name": "Bulgarian",
  },
  {
    "id": 238,
    "name": "Taj Mehmood Amroti",
    "author_name": "Taj Mehmood Amroti",
    "slug": null,
    "language_name": "Sindhi",
  },
  {
    "id": 125,
    "name": "Shaykh Abu Rahimah Mikael Aykyuni",
    "author_name": "Shaykh Abu Rahimah Mikael Aykyuni",
    "slug": null,
    "language_name": "yoruba",
  },
  {
    "id": 124,
    "name": "Muslim Shahin",
    "author_name": "Muslim Shahin",
    "slug": null,
    "language_name": "turkish",
  },
  {
    "id": 46,
    "name": "Mahmud Muhammad Abduh",
    "author_name": "Mahmud Muhammad Abduh",
    "slug": "so-mahmud-abduh",
    "language_name": "somali",
  },
  {
    "id": 113,
    "name": "Khalifah Altai",
    "author_name": "Khalifah Altai",
    "slug": null,
    "language_name": "kazakh",
  },
  {
    "id": 112,
    "name": "Shaban Britch",
    "author_name": "Shaban Britch",
    "slug": null,
    "language_name": "turkish",
  },
  {
    "id": 38,
    "name": "Maranao",
    "author_name": "Maranao",
    "slug": "mrn-unknown",
    "language_name": "maranao",
  },
  {
    "id": 89,
    "name": "Albanian Translation",
    "author_name": "Sherif Ahmeti\t",
    "slug": "quran.al.ahmeti",
    "language_name": "albanian",
  },
  {
    "id": 56,
    "name": "Chinese Translation (Simplified) - Ma Jain",
    "author_name": "Ma Jian",
    "slug": "quran.zh.ma.jain",
    "language_name": "chinese",
  },
  {
    "id": 32,
    "name": "Hausa Translation(Abubakar Gumi)",
    "author_name": "Abubakar Mahmoud Gumi",
    "slug": "quran.ha.abubakar",
    "language_name": "hausa",
  },
  {
    "id": 108,
    "name": "Ahl Al-Hadith Central Society of Nepal",
    "author_name": "Ahl Al-Hadith Central Society of Nepal",
    "slug": null,
    "language_name": "nepali",
  },
  {
    "id": 37,
    "name": "Malayalam Translation(Abdul Hameed and Kunhi)",
    "author_name": "Cheriyamundam Abdul Hameed and Kunhi Mohammed Parappoor",
    "slug": "quran.ml.abdul.hameed",
    "language_name": "malayalam",
  },
  {
    "id": 43,
    "name": "Portuguese Translation( Samir )",
    "author_name": "Samir El-Hayek",
    "slug": "quran,pt.samir",
    "language_name": "portuguese",
  },
  {
    "id": 51,
    "name": "Thai Translatio (King Fahad Quran Complex)",
    "author_name": "King Fahad Quran Complex",
    "slug": "quran.th.quran.complex",
    "language_name": "thai",
  },
  {
    "id": 111,
    "name": "Ghali Apapur Apaghuna",
    "author_name": "Ghali Apapur Apaghuna",
    "slug": null,
    "language_name": "oromo",
  },
  {
    "id": 115,
    "name": "Abubakar Mahmood Jummi",
    "author_name": "Abubakar Mahmood Jummi",
    "slug": null,
    "language_name": "hausa",
  },
  {
    "id": 31,
    "name": "Muhammad Hamidullah",
    "author_name": "Muhammad Hamidullah",
    "slug": "quran.fr.hamidullah",
    "language_name": "french",
  },
  {
    "id": 29,
    "name": "Hussein Taji Kal Dari",
    "author_name": "Hussein Taji Kal Dari",
    "slug": "fr-hussein-taji",
    "language_name": "persian",
  },
  {
    "id": 208,
    "name": "Abu Reda Muhammad ibn Ahmad",
    "author_name": "Abu Reda Muhammad ibn Ahmad",
    "slug": null,
    "language_name": "german",
  },
  {
    "id": 209,
    "name": "Othman al-Sharif",
    "author_name": "Othman al-Sharif",
    "slug": null,
    "language_name": "italian",
  },
  {
    "id": 133,
    "name": "Abdul Hameed Baqavi",
    "author_name": "Abdul Hameed Baqavi",
    "slug": null,
    "language_name": "tamil",
  },
  {
    "id": 25,
    "name": "Muhamed Mehanović",
    "author_name": "Muhamed Mehanović",
    "slug": "bs-unknown",
    "language_name": "bosnian",
  },
  {
    "id": 221,
    "name": "Hasan Abdul-Karim",
    "author_name": "Hasan Abdul-Karim",
    "slug": null,
    "language_name": "vietnamese",
  },
  {
    "id": 219,
    "name": "Hamed Choi",
    "author_name": "Hamed Choi",
    "slug": null,
    "language_name": "korean",
  },
  {
    "id": 52,
    "name": "Elmalili Hamdi Yazir",
    "author_name": "Elmalili Hamdi Yazir\t",
    "slug": "tr-hamdi",
    "language_name": "turkish",
  },
  {
    "id": 213,
    "name": "Dr. Abu Bakr Muhammad Zakaria",
    "author_name": "Dr. Abu Bakr Muhammad Zakaria",
    "slug": null,
    "language_name": "bengali",
  },
  {
    "id": 199,
    "name": "Noor International Center",
    "author_name": "Noor International Center",
    "slug": null,
    "language_name": "spanish",
  },
  {
    "id": 218,
    "name": "Saeed Sato",
    "author_name": "Saeed Sato",
    "slug": null,
    "language_name": "japanese",
  },
  {
    "id": 228,
    "name": "Ruwwad Center",
    "author_name": "Translation Pioneers Center",
    "slug": null,
    "language_name": "sinhala, sinhalese",
  },
  {
    "id": 126,
    "name": "Besim Korkut",
    "author_name": "Besim Korkut",
    "slug": null,
    "language_name": "bosnian",
  },
  {
    "id": 122,
    "name": "Maulana Azizul Haque al-Umari",
    "author_name": "Maulana Azizul Haque al-Umari",
    "slug": null,
    "language_name": "hindi",
  },
  {
    "id": 120,
    "name": "Shaykh Rafeequl Islam Habibur-Rahman",
    "author_name": "Shaykh Rafeequl Islam Habibur-Rahman",
    "slug": null,
    "language_name": "assamese",
  },
  {
    "id": 127,
    "name": "Muhammad Sodik Muhammad Yusuf",
    "author_name": "Muhammad Sodik Muhammad Yusuf",
    "slug": "",
    "language_name": "uzbek",
  },
  {
    "id": 118,
    "name": "Zakaria Abulsalam",
    "author_name": "Zakaria Abulsalam",
    "slug": null,
    "language_name": "pashto",
  },
  {
    "id": 109,
    "name": "Muhammad Makin",
    "author_name": "Muhammad Makin",
    "slug": null,
    "language_name": "chinese",
  },
  {
    "id": 27,
    "name": "Frank Bubenheim and Nadeem",
    "author_name": "Frank Bubenheim and Nadeem",
    "slug": "de-bubenheim",
    "language_name": "german",
  },
  {
    "id": 33,
    "name": "Indonesian Islamic affairs ministry",
    "author_name": "Indonesian Islamic affairs ministry",
    "slug": "quran.id",
    "language_name": "indonesian",
  },
  {
    "id": 785,
    "name": "Mawlawi Muhammad Anwar Badkhashani",
    "author_name": "Mawlawi Muhammad Anwar Badkhashani",
    "slug": null,
    "language_name": "dari",
  },
  {
    "id": 795,
    "name": "Suliman Kanti",
    "author_name": "Suliman Kanti",
    "slug": "",
    "language_name": "bambara",
  },
  {
    "id": 779,
    "name": "Rashid Maash",
    "author_name": "Rashid Maash",
    "slug": "fr-rashid-maash",
    "language_name": "french",
  },
  {
    "id": 771,
    "name": "Kannada Translation",
    "author_name": "Kannada Translation",
    "slug": "kannada-quran",
    "language_name": "kannada",
  },
  {
    "id": 782,
    "name": "Islamic and Cultural League",
    "author_name": "Islamic and Cultural League",
    "slug": "",
    "language_name": "romanian",
  },
  {
    "id": 796,
    "name": "Baba Mamady Jani",
    "author_name": "Baba Mamady Jani",
    "slug": null,
    "language_name": "bambara",
  },
  {
    "id": 798,
    "name": "Abdul Hamid Silika",
    "author_name": "Abdul Hamid Silika",
    "slug": null,
    "language_name": "yau,yuw",
  },
  {
    "id": 774,
    "name": "The Rwanda Muslims Association team",
    "author_name": "The Rwanda Muslims Association team",
    "slug": null,
    "language_name": "kinyarwanda",
  },
  {
    "id": 840,
    "name": "Abu Bakr Ibrahim Ali (Bakurube)",
    "author_name": "Abu Bakr Ibrahim Ali",
    "slug": "ml-shaikh-aboobakr-ibrahim-ali",
    "language_name": "divehi",
  },
  {
    "id": 819,
    "name": "Maulana Wahiduddin Khan",
    "author_name": "Maulana Wahiduddin Khan",
    "slug": "maulana-wahid-uddin-khan-urdu",
    "language_name": "urdu",
  },
  {
    "id": 831,
    "name": "Abul Ala Maududi(Roman Urdu)",
    "author_name": "Abul Ala Maududi",
    "slug": "maududi-roman-urdu",
    "language_name": "urdu",
  }
];
// List<Map<String, dynamic>> allRecitation = [
//   {
//     "id": 2,
//     "reciter_name": "AbdulBaset AbdulSamad",
//     "style": "Murattal",
//     //   },
//   {
//     "id": 1,
//     "reciter_name": "AbdulBaset AbdulSamad",
//     "style": "Mujawwad",
//     //   },
//   {
//     "id": 3,
//     "reciter_name": "Abdur-Rahman as-Sudais",
//     "style": null,
//     //   },
//   {
//     "id": 4,
//     "reciter_name": "Abu Bakr al-Shatri",
//     "style": null,
//     //   },
//   {
//     "id": 5,
//     "reciter_name": "Hani ar-Rifai",
//     "style": null,
//     "translated_name": {"name": "Hani ar-Rifai", "language_name": "english"}
//   },
//   {
//     "id": 12,
//     "reciter_name": "Mahmoud Khalil Al-Husary",
//     "style": "Muallim",
//     //   },
//   {
//     "id": 6,
//     "reciter_name": "Mahmoud Khalil Al-Husary",
//     "style": null,
//     //   },
//   {
//     "id": 7,
//     "reciter_name": "Mishari Rashid al-`Afasy",
//     "style": null,
//     //   },
//   {
//     "id": 9,
//     "reciter_name": "Mohamed Siddiq al-Minshawi",
//     "style": "Murattal",
//     //   },
//   {
//     "id": 8,
//     "reciter_name": "Mohamed Siddiq al-Minshawi",
//     "style": "Mujawwad",
//     //   },
//   {
//     "id": 10,
//     "reciter_name": "Sa`ud ash-Shuraym",
//     "style": null,
//     "translated_name": {"name": "Sa`ud ash-Shuraym", "language_name": "english"}
//   },
//   {
//     "id": 11,
//     "reciter_name": "Mohamed al-Tablawi",
//     "style": null,
//     //   }
// ];

List<Map<String, dynamic>> allChaptersInfo = [
  {
    "id": 1,
    "revelation_place": "makkah",
    "revelation_order": 5,
    "bismillah_pre": false,
    "name_simple": "Al-Fatihah",
    "name_complex": "Al-F\u0101ti\u0125ah",
    "name_arabic": "\u0627\u0644\u0641\u0627\u062a\u062d\u0629",
    "verses_count": 7,
    "pages": [1, 1],
  },
  {
    "id": 2,
    "revelation_place": "madinah",
    "revelation_order": 87,
    "bismillah_pre": true,
    "name_simple": "Al-Baqarah",
    "name_complex": "Al-Baqarah",
    "name_arabic": "\u0627\u0644\u0628\u0642\u0631\u0629",
    "verses_count": 286,
    "pages": [2, 49],
  },
  {
    "id": 3,
    "revelation_place": "madinah",
    "revelation_order": 89,
    "bismillah_pre": true,
    "name_simple": "Ali 'Imran",
    "name_complex": "\u0100li `Imr\u0101n",
    "name_arabic": "\u0622\u0644 \u0639\u0645\u0631\u0627\u0646",
    "verses_count": 200,
    "pages": [50, 76],
  },
  {
    "id": 4,
    "revelation_place": "madinah",
    "revelation_order": 92,
    "bismillah_pre": true,
    "name_simple": "An-Nisa",
    "name_complex": "An-Nis\u0101",
    "name_arabic": "\u0627\u0644\u0646\u0633\u0627\u0621",
    "verses_count": 176,
    "pages": [77, 106],
  },
  {
    "id": 5,
    "revelation_place": "madinah",
    "revelation_order": 112,
    "bismillah_pre": true,
    "name_simple": "Al-Ma'idah",
    "name_complex": "Al-M\u0101'idah",
    "name_arabic": "\u0627\u0644\u0645\u0627\u0626\u062f\u0629",
    "verses_count": 120,
    "pages": [106, 127],
  },
  {
    "id": 6,
    "revelation_place": "makkah",
    "revelation_order": 55,
    "bismillah_pre": true,
    "name_simple": "Al-An'am",
    "name_complex": "Al-'An`\u0101m",
    "name_arabic": "\u0627\u0644\u0623\u0646\u0639\u0627\u0645",
    "verses_count": 165,
    "pages": [128, 150],
  },
  {
    "id": 7,
    "revelation_place": "makkah",
    "revelation_order": 39,
    "bismillah_pre": true,
    "name_simple": "Al-A'raf",
    "name_complex": "Al-'A`r\u0101f",
    "name_arabic": "\u0627\u0644\u0623\u0639\u0631\u0627\u0641",
    "verses_count": 206,
    "pages": [151, 176],
  },
  {
    "id": 8,
    "revelation_place": "madinah",
    "revelation_order": 88,
    "bismillah_pre": true,
    "name_simple": "Al-Anfal",
    "name_complex": "Al-'Anf\u0101l",
    "name_arabic": "\u0627\u0644\u0623\u0646\u0641\u0627\u0644",
    "verses_count": 75,
    "pages": [177, 186],
  },
  {
    "id": 9,
    "revelation_place": "madinah",
    "revelation_order": 113,
    "bismillah_pre": false,
    "name_simple": "At-Tawbah",
    "name_complex": "At-Tawbah",
    "name_arabic": "\u0627\u0644\u062a\u0648\u0628\u0629",
    "verses_count": 129,
    "pages": [187, 207],
  },
  {
    "id": 10,
    "revelation_place": "makkah",
    "revelation_order": 51,
    "bismillah_pre": true,
    "name_simple": "Yunus",
    "name_complex": "Y\u016bnus",
    "name_arabic": "\u064a\u0648\u0646\u0633",
    "verses_count": 109,
    "pages": [208, 221],
  },
  {
    "id": 11,
    "revelation_place": "makkah",
    "revelation_order": 52,
    "bismillah_pre": true,
    "name_simple": "Hud",
    "name_complex": "H\u016bd",
    "name_arabic": "\u0647\u0648\u062f",
    "verses_count": 123,
    "pages": [221, 235],
  },
  {
    "id": 12,
    "revelation_place": "makkah",
    "revelation_order": 53,
    "bismillah_pre": true,
    "name_simple": "Yusuf",
    "name_complex": "Y\u016bsuf",
    "name_arabic": "\u064a\u0648\u0633\u0641",
    "verses_count": 111,
    "pages": [235, 248],
  },
  {
    "id": 13,
    "revelation_place": "madinah",
    "revelation_order": 96,
    "bismillah_pre": true,
    "name_simple": "Ar-Ra'd",
    "name_complex": "Ar-Ra`d",
    "name_arabic": "\u0627\u0644\u0631\u0639\u062f",
    "verses_count": 43,
    "pages": [249, 255],
  },
  {
    "id": 14,
    "revelation_place": "makkah",
    "revelation_order": 72,
    "bismillah_pre": true,
    "name_simple": "Ibrahim",
    "name_complex": "Ibr\u0101h\u012bm",
    "name_arabic": "\u0627\u0628\u0631\u0627\u0647\u064a\u0645",
    "verses_count": 52,
    "pages": [255, 261],
  },
  {
    "id": 15,
    "revelation_place": "makkah",
    "revelation_order": 54,
    "bismillah_pre": true,
    "name_simple": "Al-Hijr",
    "name_complex": "Al-\u0124ijr",
    "name_arabic": "\u0627\u0644\u062d\u062c\u0631",
    "verses_count": 99,
    "pages": [262, 267],
  },
  {
    "id": 16,
    "revelation_place": "makkah",
    "revelation_order": 70,
    "bismillah_pre": true,
    "name_simple": "An-Nahl",
    "name_complex": "An-Na\u0125l",
    "name_arabic": "\u0627\u0644\u0646\u062d\u0644",
    "verses_count": 128,
    "pages": [267, 281],
  },
  {
    "id": 17,
    "revelation_place": "makkah",
    "revelation_order": 50,
    "bismillah_pre": true,
    "name_simple": "Al-Isra",
    "name_complex": "Al-'Isr\u0101",
    "name_arabic": "\u0627\u0644\u0625\u0633\u0631\u0627\u0621",
    "verses_count": 111,
    "pages": [282, 293],
  },
  {
    "id": 18,
    "revelation_place": "makkah",
    "revelation_order": 69,
    "bismillah_pre": true,
    "name_simple": "Al-Kahf",
    "name_complex": "Al-Kahf",
    "name_arabic": "\u0627\u0644\u0643\u0647\u0641",
    "verses_count": 110,
    "pages": [293, 304],
  },
  {
    "id": 19,
    "revelation_place": "makkah",
    "revelation_order": 44,
    "bismillah_pre": true,
    "name_simple": "Maryam",
    "name_complex": "Maryam",
    "name_arabic": "\u0645\u0631\u064a\u0645",
    "verses_count": 98,
    "pages": [305, 312],
  },
  {
    "id": 20,
    "revelation_place": "makkah",
    "revelation_order": 45,
    "bismillah_pre": true,
    "name_simple": "Taha",
    "name_complex": "\u0162\u0101h\u0101",
    "name_arabic": "\u0637\u0647",
    "verses_count": 135,
    "pages": [312, 321],
  },
  {
    "id": 21,
    "revelation_place": "makkah",
    "revelation_order": 73,
    "bismillah_pre": true,
    "name_simple": "Al-Anbya",
    "name_complex": "Al-'Anby\u0101",
    "name_arabic": "\u0627\u0644\u0623\u0646\u0628\u064a\u0627\u0621",
    "verses_count": 112,
    "pages": [322, 331],
  },
  {
    "id": 22,
    "revelation_place": "madinah",
    "revelation_order": 103,
    "bismillah_pre": true,
    "name_simple": "Al-Hajj",
    "name_complex": "Al-\u0124ajj",
    "name_arabic": "\u0627\u0644\u062d\u062c",
    "verses_count": 78,
    "pages": [332, 341],
  },
  {
    "id": 23,
    "revelation_place": "makkah",
    "revelation_order": 74,
    "bismillah_pre": true,
    "name_simple": "Al-Mu'minun",
    "name_complex": "Al-Mu'min\u016bn",
    "name_arabic": "\u0627\u0644\u0645\u0624\u0645\u0646\u0648\u0646",
    "verses_count": 118,
    "pages": [342, 349],
  },
  {
    "id": 24,
    "revelation_place": "madinah",
    "revelation_order": 102,
    "bismillah_pre": true,
    "name_simple": "An-Nur",
    "name_complex": "An-N\u016br",
    "name_arabic": "\u0627\u0644\u0646\u0648\u0631",
    "verses_count": 64,
    "pages": [350, 359],
  },
  {
    "id": 25,
    "revelation_place": "makkah",
    "revelation_order": 42,
    "bismillah_pre": true,
    "name_simple": "Al-Furqan",
    "name_complex": "Al-Furq\u0101n",
    "name_arabic": "\u0627\u0644\u0641\u0631\u0642\u0627\u0646",
    "verses_count": 77,
    "pages": [359, 366],
  },
  {
    "id": 26,
    "revelation_place": "makkah",
    "revelation_order": 47,
    "bismillah_pre": true,
    "name_simple": "Ash-Shu'ara",
    "name_complex": "Ash-Shu`ar\u0101",
    "name_arabic": "\u0627\u0644\u0634\u0639\u0631\u0627\u0621",
    "verses_count": 227,
    "pages": [367, 376],
  },
  {
    "id": 27,
    "revelation_place": "makkah",
    "revelation_order": 48,
    "bismillah_pre": true,
    "name_simple": "An-Naml",
    "name_complex": "An-Naml",
    "name_arabic": "\u0627\u0644\u0646\u0645\u0644",
    "verses_count": 93,
    "pages": [377, 385],
  },
  {
    "id": 28,
    "revelation_place": "makkah",
    "revelation_order": 49,
    "bismillah_pre": true,
    "name_simple": "Al-Qasas",
    "name_complex": "Al-Qa\u015fa\u015f",
    "name_arabic": "\u0627\u0644\u0642\u0635\u0635",
    "verses_count": 88,
    "pages": [385, 396],
  },
  {
    "id": 29,
    "revelation_place": "makkah",
    "revelation_order": 85,
    "bismillah_pre": true,
    "name_simple": "Al-'Ankabut",
    "name_complex": "Al-`Ankab\u016bt",
    "name_arabic": "\u0627\u0644\u0639\u0646\u0643\u0628\u0648\u062a",
    "verses_count": 69,
    "pages": [396, 404],
  },
  {
    "id": 30,
    "revelation_place": "makkah",
    "revelation_order": 84,
    "bismillah_pre": true,
    "name_simple": "Ar-Rum",
    "name_complex": "Ar-R\u016bm",
    "name_arabic": "\u0627\u0644\u0631\u0648\u0645",
    "verses_count": 60,
    "pages": [404, 410],
  },
  {
    "id": 31,
    "revelation_place": "makkah",
    "revelation_order": 57,
    "bismillah_pre": true,
    "name_simple": "Luqman",
    "name_complex": "Luqm\u0101n",
    "name_arabic": "\u0644\u0642\u0645\u0627\u0646",
    "verses_count": 34,
    "pages": [411, 414],
  },
  {
    "id": 32,
    "revelation_place": "makkah",
    "revelation_order": 75,
    "bismillah_pre": true,
    "name_simple": "As-Sajdah",
    "name_complex": "As-Sajdah",
    "name_arabic": "\u0627\u0644\u0633\u062c\u062f\u0629",
    "verses_count": 30,
    "pages": [415, 417],
  },
  {
    "id": 33,
    "revelation_place": "madinah",
    "revelation_order": 90,
    "bismillah_pre": true,
    "name_simple": "Al-Ahzab",
    "name_complex": "Al-'A\u0125z\u0101b",
    "name_arabic": "\u0627\u0644\u0623\u062d\u0632\u0627\u0628",
    "verses_count": 73,
    "pages": [418, 427],
  },
  {
    "id": 34,
    "revelation_place": "makkah",
    "revelation_order": 58,
    "bismillah_pre": true,
    "name_simple": "Saba",
    "name_complex": "Saba",
    "name_arabic": "\u0633\u0628\u0625",
    "verses_count": 54,
    "pages": [428, 434],
  },
  {
    "id": 35,
    "revelation_place": "makkah",
    "revelation_order": 43,
    "bismillah_pre": true,
    "name_simple": "Fatir",
    "name_complex": "F\u0101\u0163ir",
    "name_arabic": "\u0641\u0627\u0637\u0631",
    "verses_count": 45,
    "pages": [434, 440],
  },
  {
    "id": 36,
    "revelation_place": "makkah",
    "revelation_order": 41,
    "bismillah_pre": true,
    "name_simple": "Ya-Sin",
    "name_complex": "Y\u0101-S\u012bn",
    "name_arabic": "\u064a\u0633",
    "verses_count": 83,
    "pages": [440, 445],
  },
  {
    "id": 37,
    "revelation_place": "makkah",
    "revelation_order": 56,
    "bismillah_pre": true,
    "name_simple": "As-Saffat",
    "name_complex": "A\u015f-\u015e\u0101ff\u0101t",
    "name_arabic": "\u0627\u0644\u0635\u0627\u0641\u0627\u062a",
    "verses_count": 182,
    "pages": [446, 452],
  },
  {
    "id": 38,
    "revelation_place": "makkah",
    "revelation_order": 38,
    "bismillah_pre": true,
    "name_simple": "Sad",
    "name_complex": "\u015e\u0101d",
    "name_arabic": "\u0635",
    "verses_count": 88,
    "pages": [453, 458],
  },
  {
    "id": 39,
    "revelation_place": "makkah",
    "revelation_order": 59,
    "bismillah_pre": true,
    "name_simple": "Az-Zumar",
    "name_complex": "Az-Zumar",
    "name_arabic": "\u0627\u0644\u0632\u0645\u0631",
    "verses_count": 75,
    "pages": [458, 467],
  },
  {
    "id": 40,
    "revelation_place": "makkah",
    "revelation_order": 60,
    "bismillah_pre": true,
    "name_simple": "Ghafir",
    "name_complex": "Gh\u0101fir",
    "name_arabic": "\u063a\u0627\u0641\u0631",
    "verses_count": 85,
    "pages": [467, 476],
  },
  {
    "id": 41,
    "revelation_place": "makkah",
    "revelation_order": 61,
    "bismillah_pre": true,
    "name_simple": "Fussilat",
    "name_complex": "Fu\u015f\u015filat",
    "name_arabic": "\u0641\u0635\u0644\u062a",
    "verses_count": 54,
    "pages": [477, 482],
  },
  {
    "id": 42,
    "revelation_place": "makkah",
    "revelation_order": 62,
    "bismillah_pre": true,
    "name_simple": "Ash-Shuraa",
    "name_complex": "Ash-Sh\u016bra\u00e1",
    "name_arabic": "\u0627\u0644\u0634\u0648\u0631\u0649",
    "verses_count": 53,
    "pages": [483, 489],
  },
  {
    "id": 43,
    "revelation_place": "makkah",
    "revelation_order": 63,
    "bismillah_pre": true,
    "name_simple": "Az-Zukhruf",
    "name_complex": "Az-Zukhruf",
    "name_arabic": "\u0627\u0644\u0632\u062e\u0631\u0641",
    "verses_count": 89,
    "pages": [489, 495],
  },
  {
    "id": 44,
    "revelation_place": "makkah",
    "revelation_order": 64,
    "bismillah_pre": true,
    "name_simple": "Ad-Dukhan",
    "name_complex": "Ad-Dukh\u0101n",
    "name_arabic": "\u0627\u0644\u062f\u062e\u0627\u0646",
    "verses_count": 59,
    "pages": [496, 498],
  },
  {
    "id": 45,
    "revelation_place": "makkah",
    "revelation_order": 65,
    "bismillah_pre": true,
    "name_simple": "Al-Jathiyah",
    "name_complex": "Al-J\u0101thiyah",
    "name_arabic": "\u0627\u0644\u062c\u0627\u062b\u064a\u0629",
    "verses_count": 37,
    "pages": [499, 502],
  },
  {
    "id": 46,
    "revelation_place": "makkah",
    "revelation_order": 66,
    "bismillah_pre": true,
    "name_simple": "Al-Ahqaf",
    "name_complex": "Al-'A\u0125q\u0101f",
    "name_arabic": "\u0627\u0644\u0623\u062d\u0642\u0627\u0641",
    "verses_count": 35,
    "pages": [502, 506],
  },
  {
    "id": 47,
    "revelation_place": "madinah",
    "revelation_order": 95,
    "bismillah_pre": true,
    "name_simple": "Muhammad",
    "name_complex": "Mu\u0125ammad",
    "name_arabic": "\u0645\u062d\u0645\u062f",
    "verses_count": 38,
    "pages": [507, 510],
  },
  {
    "id": 48,
    "revelation_place": "madinah",
    "revelation_order": 111,
    "bismillah_pre": true,
    "name_simple": "Al-Fath",
    "name_complex": "Al-Fat\u0125",
    "name_arabic": "\u0627\u0644\u0641\u062a\u062d",
    "verses_count": 29,
    "pages": [511, 515],
  },
  {
    "id": 49,
    "revelation_place": "madinah",
    "revelation_order": 106,
    "bismillah_pre": true,
    "name_simple": "Al-Hujurat",
    "name_complex": "Al-\u0124ujur\u0101t",
    "name_arabic": "\u0627\u0644\u062d\u062c\u0631\u0627\u062a",
    "verses_count": 18,
    "pages": [515, 517],
  },
  {
    "id": 50,
    "revelation_place": "makkah",
    "revelation_order": 34,
    "bismillah_pre": true,
    "name_simple": "Qaf",
    "name_complex": "Q\u0101f",
    "name_arabic": "\u0642",
    "verses_count": 45,
    "pages": [518, 520],
  },
  {
    "id": 51,
    "revelation_place": "makkah",
    "revelation_order": 67,
    "bismillah_pre": true,
    "name_simple": "Adh-Dhariyat",
    "name_complex": "Adh-Dh\u0101riy\u0101t",
    "name_arabic": "\u0627\u0644\u0630\u0627\u0631\u064a\u0627\u062a",
    "verses_count": 60,
    "pages": [520, 523],
  },
  {
    "id": 52,
    "revelation_place": "makkah",
    "revelation_order": 76,
    "bismillah_pre": true,
    "name_simple": "At-Tur",
    "name_complex": "A\u0163-\u0162\u016br",
    "name_arabic": "\u0627\u0644\u0637\u0648\u0631",
    "verses_count": 49,
    "pages": [523, 525],
  },
  {
    "id": 53,
    "revelation_place": "makkah",
    "revelation_order": 23,
    "bismillah_pre": true,
    "name_simple": "An-Najm",
    "name_complex": "An-Najm",
    "name_arabic": "\u0627\u0644\u0646\u062c\u0645",
    "verses_count": 62,
    "pages": [526, 528],
  },
  {
    "id": 54,
    "revelation_place": "makkah",
    "revelation_order": 37,
    "bismillah_pre": true,
    "name_simple": "Al-Qamar",
    "name_complex": "Al-Qamar",
    "name_arabic": "\u0627\u0644\u0642\u0645\u0631",
    "verses_count": 55,
    "pages": [528, 531],
  },
  {
    "id": 55,
    "revelation_place": "madinah",
    "revelation_order": 97,
    "bismillah_pre": true,
    "name_simple": "Ar-Rahman",
    "name_complex": "Ar-Ra\u0125m\u0101n",
    "name_arabic": "\u0627\u0644\u0631\u062d\u0645\u0646",
    "verses_count": 78,
    "pages": [531, 534],
  },
  {
    "id": 56,
    "revelation_place": "makkah",
    "revelation_order": 46,
    "bismillah_pre": true,
    "name_simple": "Al-Waqi'ah",
    "name_complex": "Al-W\u0101qi`ah",
    "name_arabic": "\u0627\u0644\u0648\u0627\u0642\u0639\u0629",
    "verses_count": 96,
    "pages": [534, 537],
  },
  {
    "id": 57,
    "revelation_place": "madinah",
    "revelation_order": 94,
    "bismillah_pre": true,
    "name_simple": "Al-Hadid",
    "name_complex": "Al-\u0124ad\u012bd",
    "name_arabic": "\u0627\u0644\u062d\u062f\u064a\u062f",
    "verses_count": 29,
    "pages": [537, 541],
  },
  {
    "id": 58,
    "revelation_place": "madinah",
    "revelation_order": 105,
    "bismillah_pre": true,
    "name_simple": "Al-Mujadila",
    "name_complex": "Al-Muj\u0101dila",
    "name_arabic": "\u0627\u0644\u0645\u062c\u0627\u062f\u0644\u0629",
    "verses_count": 22,
    "pages": [542, 545],
  },
  {
    "id": 59,
    "revelation_place": "madinah",
    "revelation_order": 101,
    "bismillah_pre": true,
    "name_simple": "Al-Hashr",
    "name_complex": "Al-\u0124ashr",
    "name_arabic": "\u0627\u0644\u062d\u0634\u0631",
    "verses_count": 24,
    "pages": [545, 548],
  },
  {
    "id": 60,
    "revelation_place": "madinah",
    "revelation_order": 91,
    "bismillah_pre": true,
    "name_simple": "Al-Mumtahanah",
    "name_complex": "Al-Mumta\u0125anah",
    "name_arabic": "\u0627\u0644\u0645\u0645\u062a\u062d\u0646\u0629",
    "verses_count": 13,
    "pages": [549, 551],
  },
  {
    "id": 61,
    "revelation_place": "madinah",
    "revelation_order": 109,
    "bismillah_pre": true,
    "name_simple": "As-Saf",
    "name_complex": "A\u015f-\u015eaf",
    "name_arabic": "\u0627\u0644\u0635\u0641",
    "verses_count": 14,
    "pages": [551, 552],
  },
  {
    "id": 62,
    "revelation_place": "madinah",
    "revelation_order": 110,
    "bismillah_pre": true,
    "name_simple": "Al-Jumu'ah",
    "name_complex": "Al-Jumu`ah",
    "name_arabic": "\u0627\u0644\u062c\u0645\u0639\u0629",
    "verses_count": 11,
    "pages": [553, 554],
  },
  {
    "id": 63,
    "revelation_place": "madinah",
    "revelation_order": 104,
    "bismillah_pre": true,
    "name_simple": "Al-Munafiqun",
    "name_complex": "Al-Mun\u0101fiq\u016bn",
    "name_arabic": "\u0627\u0644\u0645\u0646\u0627\u0641\u0642\u0648\u0646",
    "verses_count": 11,
    "pages": [554, 555],
  },
  {
    "id": 64,
    "revelation_place": "madinah",
    "revelation_order": 108,
    "bismillah_pre": true,
    "name_simple": "At-Taghabun",
    "name_complex": "At-Tagh\u0101bun",
    "name_arabic": "\u0627\u0644\u062a\u063a\u0627\u0628\u0646",
    "verses_count": 18,
    "pages": [556, 557],
  },
  {
    "id": 65,
    "revelation_place": "madinah",
    "revelation_order": 99,
    "bismillah_pre": true,
    "name_simple": "At-Talaq",
    "name_complex": "A\u0163-\u0162al\u0101q",
    "name_arabic": "\u0627\u0644\u0637\u0644\u0627\u0642",
    "verses_count": 12,
    "pages": [558, 559],
  },
  {
    "id": 66,
    "revelation_place": "madinah",
    "revelation_order": 107,
    "bismillah_pre": true,
    "name_simple": "At-Tahrim",
    "name_complex": "At-Ta\u0125r\u012bm",
    "name_arabic": "\u0627\u0644\u062a\u062d\u0631\u064a\u0645",
    "verses_count": 12,
    "pages": [560, 561],
  },
  {
    "id": 67,
    "revelation_place": "makkah",
    "revelation_order": 77,
    "bismillah_pre": true,
    "name_simple": "Al-Mulk",
    "name_complex": "Al-Mulk",
    "name_arabic": "\u0627\u0644\u0645\u0644\u0643",
    "verses_count": 30,
    "pages": [562, 564],
  },
  {
    "id": 68,
    "revelation_place": "makkah",
    "revelation_order": 2,
    "bismillah_pre": true,
    "name_simple": "Al-Qalam",
    "name_complex": "Al-Qalam",
    "name_arabic": "\u0627\u0644\u0642\u0644\u0645",
    "verses_count": 52,
    "pages": [564, 566],
  },
  {
    "id": 69,
    "revelation_place": "makkah",
    "revelation_order": 78,
    "bismillah_pre": true,
    "name_simple": "Al-Haqqah",
    "name_complex": "Al-\u0124\u0101qqah",
    "name_arabic": "\u0627\u0644\u062d\u0627\u0642\u0629",
    "verses_count": 52,
    "pages": [566, 568],
  },
  {
    "id": 70,
    "revelation_place": "makkah",
    "revelation_order": 79,
    "bismillah_pre": true,
    "name_simple": "Al-Ma'arij",
    "name_complex": "Al-Ma`\u0101rij",
    "name_arabic": "\u0627\u0644\u0645\u0639\u0627\u0631\u062c",
    "verses_count": 44,
    "pages": [568, 570],
  },
  {
    "id": 71,
    "revelation_place": "makkah",
    "revelation_order": 71,
    "bismillah_pre": true,
    "name_simple": "Nuh",
    "name_complex": "N\u016b\u0125",
    "name_arabic": "\u0646\u0648\u062d",
    "verses_count": 28,
    "pages": [570, 571],
  },
  {
    "id": 72,
    "revelation_place": "makkah",
    "revelation_order": 40,
    "bismillah_pre": true,
    "name_simple": "Al-Jinn",
    "name_complex": "Al-Jinn",
    "name_arabic": "\u0627\u0644\u062c\u0646",
    "verses_count": 28,
    "pages": [572, 573],
  },
  {
    "id": 73,
    "revelation_place": "makkah",
    "revelation_order": 3,
    "bismillah_pre": true,
    "name_simple": "Al-Muzzammil",
    "name_complex": "Al-Muzzammil",
    "name_arabic": "\u0627\u0644\u0645\u0632\u0645\u0644",
    "verses_count": 20,
    "pages": [574, 575],
  },
  {
    "id": 74,
    "revelation_place": "makkah",
    "revelation_order": 4,
    "bismillah_pre": true,
    "name_simple": "Al-Muddaththir",
    "name_complex": "Al-Muddaththir",
    "name_arabic": "\u0627\u0644\u0645\u062f\u062b\u0631",
    "verses_count": 56,
    "pages": [575, 577],
  },
  {
    "id": 75,
    "revelation_place": "makkah",
    "revelation_order": 31,
    "bismillah_pre": true,
    "name_simple": "Al-Qiyamah",
    "name_complex": "Al-Qiy\u0101mah",
    "name_arabic": "\u0627\u0644\u0642\u064a\u0627\u0645\u0629",
    "verses_count": 40,
    "pages": [577, 578],
  },
  {
    "id": 76,
    "revelation_place": "madinah",
    "revelation_order": 98,
    "bismillah_pre": true,
    "name_simple": "Al-Insan",
    "name_complex": "Al-'Ins\u0101n",
    "name_arabic": "\u0627\u0644\u0627\u0646\u0633\u0627\u0646",
    "verses_count": 31,
    "pages": [578, 580],
  },
  {
    "id": 77,
    "revelation_place": "makkah",
    "revelation_order": 33,
    "bismillah_pre": true,
    "name_simple": "Al-Mursalat",
    "name_complex": "Al-Mursal\u0101t",
    "name_arabic": "\u0627\u0644\u0645\u0631\u0633\u0644\u0627\u062a",
    "verses_count": 50,
    "pages": [580, 581],
  },
  {
    "id": 78,
    "revelation_place": "makkah",
    "revelation_order": 80,
    "bismillah_pre": true,
    "name_simple": "An-Naba",
    "name_complex": "An-Naba",
    "name_arabic": "\u0627\u0644\u0646\u0628\u0625",
    "verses_count": 40,
    "pages": [582, 583],
  },
  {
    "id": 79,
    "revelation_place": "makkah",
    "revelation_order": 81,
    "bismillah_pre": true,
    "name_simple": "An-Nazi'at",
    "name_complex": "An-N\u0101zi`\u0101t",
    "name_arabic": "\u0627\u0644\u0646\u0627\u0632\u0639\u0627\u062a",
    "verses_count": 46,
    "pages": [583, 584],
  },
  {
    "id": 80,
    "revelation_place": "makkah",
    "revelation_order": 24,
    "bismillah_pre": true,
    "name_simple": "'Abasa",
    "name_complex": "`Abasa",
    "name_arabic": "\u0639\u0628\u0633",
    "verses_count": 42,
    "pages": [585, 585],
  },
  {
    "id": 81,
    "revelation_place": "makkah",
    "revelation_order": 7,
    "bismillah_pre": true,
    "name_simple": "At-Takwir",
    "name_complex": "At-Takw\u012br",
    "name_arabic": "\u0627\u0644\u062a\u0643\u0648\u064a\u0631",
    "verses_count": 29,
    "pages": [586, 586],
  },
  {
    "id": 82,
    "revelation_place": "makkah",
    "revelation_order": 82,
    "bismillah_pre": true,
    "name_simple": "Al-Infitar",
    "name_complex": "Al-'Infi\u0163\u0101r",
    "name_arabic": "\u0627\u0644\u0625\u0646\u0641\u0637\u0627\u0631",
    "verses_count": 19,
    "pages": [587, 587],
  },
  {
    "id": 83,
    "revelation_place": "makkah",
    "revelation_order": 86,
    "bismillah_pre": true,
    "name_simple": "Al-Mutaffifin",
    "name_complex": "Al-Mu\u0163affif\u012bn",
    "name_arabic": "\u0627\u0644\u0645\u0637\u0641\u0641\u064a\u0646",
    "verses_count": 36,
    "pages": [587, 589],
  },
  {
    "id": 84,
    "revelation_place": "makkah",
    "revelation_order": 83,
    "bismillah_pre": true,
    "name_simple": "Al-Inshiqaq",
    "name_complex": "Al-'Inshiq\u0101q",
    "name_arabic": "\u0627\u0644\u0625\u0646\u0634\u0642\u0627\u0642",
    "verses_count": 25,
    "pages": [589, 589],
  },
  {
    "id": 85,
    "revelation_place": "makkah",
    "revelation_order": 27,
    "bismillah_pre": true,
    "name_simple": "Al-Buruj",
    "name_complex": "Al-Bur\u016bj",
    "name_arabic": "\u0627\u0644\u0628\u0631\u0648\u062c",
    "verses_count": 22,
    "pages": [590, 590],
  },
  {
    "id": 86,
    "revelation_place": "makkah",
    "revelation_order": 36,
    "bismillah_pre": true,
    "name_simple": "At-Tariq",
    "name_complex": "A\u0163-\u0162\u0101riq",
    "name_arabic": "\u0627\u0644\u0637\u0627\u0631\u0642",
    "verses_count": 17,
    "pages": [591, 591],
  },
  {
    "id": 87,
    "revelation_place": "makkah",
    "revelation_order": 8,
    "bismillah_pre": true,
    "name_simple": "Al-A'la",
    "name_complex": "Al-'A`l\u00e1",
    "name_arabic": "\u0627\u0644\u0623\u0639\u0644\u0649",
    "verses_count": 19,
    "pages": [591, 592],
  },
  {
    "id": 88,
    "revelation_place": "makkah",
    "revelation_order": 68,
    "bismillah_pre": true,
    "name_simple": "Al-Ghashiyah",
    "name_complex": "Al-Gh\u0101shiyah",
    "name_arabic": "\u0627\u0644\u063a\u0627\u0634\u064a\u0629",
    "verses_count": 26,
    "pages": [592, 592],
  },
  {
    "id": 89,
    "revelation_place": "makkah",
    "revelation_order": 10,
    "bismillah_pre": true,
    "name_simple": "Al-Fajr",
    "name_complex": "Al-Fajr",
    "name_arabic": "\u0627\u0644\u0641\u062c\u0631",
    "verses_count": 30,
    "pages": [593, 594],
  },
  {
    "id": 90,
    "revelation_place": "makkah",
    "revelation_order": 35,
    "bismillah_pre": true,
    "name_simple": "Al-Balad",
    "name_complex": "Al-Balad",
    "name_arabic": "\u0627\u0644\u0628\u0644\u062f",
    "verses_count": 20,
    "pages": [594, 594],
  },
  {
    "id": 91,
    "revelation_place": "makkah",
    "revelation_order": 26,
    "bismillah_pre": true,
    "name_simple": "Ash-Shams",
    "name_complex": "Ash-Shams",
    "name_arabic": "\u0627\u0644\u0634\u0645\u0633",
    "verses_count": 15,
    "pages": [595, 595],
  },
  {
    "id": 92,
    "revelation_place": "makkah",
    "revelation_order": 9,
    "bismillah_pre": true,
    "name_simple": "Al-Layl",
    "name_complex": "Al-Layl",
    "name_arabic": "\u0627\u0644\u0644\u064a\u0644",
    "verses_count": 21,
    "pages": [595, 596],
  },
  {
    "id": 93,
    "revelation_place": "makkah",
    "revelation_order": 11,
    "bismillah_pre": true,
    "name_simple": "Ad-Duhaa",
    "name_complex": "A\u0111-\u0110u\u0125a\u00e1",
    "name_arabic": "\u0627\u0644\u0636\u062d\u0649",
    "verses_count": 11,
    "pages": [596, 596],
  },
  {
    "id": 94,
    "revelation_place": "makkah",
    "revelation_order": 12,
    "bismillah_pre": true,
    "name_simple": "Ash-Sharh",
    "name_complex": "Ash-Shar\u0125",
    "name_arabic": "\u0627\u0644\u0634\u0631\u062d",
    "verses_count": 8,
    "pages": [596, 596],
  },
  {
    "id": 95,
    "revelation_place": "makkah",
    "revelation_order": 28,
    "bismillah_pre": true,
    "name_simple": "At-Tin",
    "name_complex": "At-T\u012bn",
    "name_arabic": "\u0627\u0644\u062a\u064a\u0646",
    "verses_count": 8,
    "pages": [597, 597],
  },
  {
    "id": 96,
    "revelation_place": "makkah",
    "revelation_order": 1,
    "bismillah_pre": true,
    "name_simple": "Al-'Alaq",
    "name_complex": "Al-`Alaq",
    "name_arabic": "\u0627\u0644\u0639\u0644\u0642",
    "verses_count": 19,
    "pages": [597, 597],
  },
  {
    "id": 97,
    "revelation_place": "makkah",
    "revelation_order": 25,
    "bismillah_pre": true,
    "name_simple": "Al-Qadr",
    "name_complex": "Al-Qadr",
    "name_arabic": "\u0627\u0644\u0642\u062f\u0631",
    "verses_count": 5,
    "pages": [598, 598],
  },
  {
    "id": 98,
    "revelation_place": "madinah",
    "revelation_order": 100,
    "bismillah_pre": true,
    "name_simple": "Al-Bayyinah",
    "name_complex": "Al-Bayyinah",
    "name_arabic": "\u0627\u0644\u0628\u064a\u0646\u0629",
    "verses_count": 8,
    "pages": [598, 599],
  },
  {
    "id": 99,
    "revelation_place": "madinah",
    "revelation_order": 93,
    "bismillah_pre": true,
    "name_simple": "Az-Zalzalah",
    "name_complex": "Az-Zalzalah",
    "name_arabic": "\u0627\u0644\u0632\u0644\u0632\u0644\u0629",
    "verses_count": 8,
    "pages": [599, 599],
  },
  {
    "id": 100,
    "revelation_place": "makkah",
    "revelation_order": 14,
    "bismillah_pre": true,
    "name_simple": "Al-'Adiyat",
    "name_complex": "Al-`\u0100diy\u0101t",
    "name_arabic": "\u0627\u0644\u0639\u0627\u062f\u064a\u0627\u062a",
    "verses_count": 11,
    "pages": [599, 600],
  },
  {
    "id": 101,
    "revelation_place": "makkah",
    "revelation_order": 30,
    "bismillah_pre": true,
    "name_simple": "Al-Qari'ah",
    "name_complex": "Al-Q\u0101ri`ah",
    "name_arabic": "\u0627\u0644\u0642\u0627\u0631\u0639\u0629",
    "verses_count": 11,
    "pages": [600, 600],
  },
  {
    "id": 102,
    "revelation_place": "makkah",
    "revelation_order": 16,
    "bismillah_pre": true,
    "name_simple": "At-Takathur",
    "name_complex": "At-Tak\u0101thur",
    "name_arabic": "\u0627\u0644\u062a\u0643\u0627\u062b\u0631",
    "verses_count": 8,
    "pages": [600, 600],
  },
  {
    "id": 103,
    "revelation_place": "makkah",
    "revelation_order": 13,
    "bismillah_pre": true,
    "name_simple": "Al-'Asr",
    "name_complex": "Al-`A\u015fr",
    "name_arabic": "\u0627\u0644\u0639\u0635\u0631",
    "verses_count": 3,
    "pages": [601, 601],
  },
  {
    "id": 104,
    "revelation_place": "makkah",
    "revelation_order": 32,
    "bismillah_pre": true,
    "name_simple": "Al-Humazah",
    "name_complex": "Al-Humazah",
    "name_arabic": "\u0627\u0644\u0647\u0645\u0632\u0629",
    "verses_count": 9,
    "pages": [601, 601],
  },
  {
    "id": 105,
    "revelation_place": "makkah",
    "revelation_order": 19,
    "bismillah_pre": true,
    "name_simple": "Al-Fil",
    "name_complex": "Al-F\u012bl",
    "name_arabic": "\u0627\u0644\u0641\u064a\u0644",
    "verses_count": 5,
    "pages": [601, 601],
  },
  {
    "id": 106,
    "revelation_place": "makkah",
    "revelation_order": 29,
    "bismillah_pre": true,
    "name_simple": "Quraysh",
    "name_complex": "Quraysh",
    "name_arabic": "\u0642\u0631\u064a\u0634",
    "verses_count": 4,
    "pages": [602, 602],
  },
  {
    "id": 107,
    "revelation_place": "makkah",
    "revelation_order": 17,
    "bismillah_pre": true,
    "name_simple": "Al-Ma'un",
    "name_complex": "Al-M\u0101`\u016bn",
    "name_arabic": "\u0627\u0644\u0645\u0627\u0639\u0648\u0646",
    "verses_count": 7,
    "pages": [602, 602],
  },
  {
    "id": 108,
    "revelation_place": "makkah",
    "revelation_order": 15,
    "bismillah_pre": true,
    "name_simple": "Al-Kawthar",
    "name_complex": "Al-Kawthar",
    "name_arabic": "\u0627\u0644\u0643\u0648\u062b\u0631",
    "verses_count": 3,
    "pages": [602, 602],
  },
  {
    "id": 109,
    "revelation_place": "makkah",
    "revelation_order": 18,
    "bismillah_pre": true,
    "name_simple": "Al-Kafirun",
    "name_complex": "Al-K\u0101fir\u016bn",
    "name_arabic": "\u0627\u0644\u0643\u0627\u0641\u0631\u0648\u0646",
    "verses_count": 6,
    "pages": [603, 603],
  },
  {
    "id": 110,
    "revelation_place": "madinah",
    "revelation_order": 114,
    "bismillah_pre": true,
    "name_simple": "An-Nasr",
    "name_complex": "An-Na\u015fr",
    "name_arabic": "\u0627\u0644\u0646\u0635\u0631",
    "verses_count": 3,
    "pages": [603, 603],
  },
  {
    "id": 111,
    "revelation_place": "makkah",
    "revelation_order": 6,
    "bismillah_pre": true,
    "name_simple": "Al-Masad",
    "name_complex": "Al-Masad",
    "name_arabic": "\u0627\u0644\u0645\u0633\u062f",
    "verses_count": 5,
    "pages": [603, 603],
  },
  {
    "id": 112,
    "revelation_place": "makkah",
    "revelation_order": 22,
    "bismillah_pre": true,
    "name_simple": "Al-Ikhlas",
    "name_complex": "Al-'Ikhl\u0101\u015f",
    "name_arabic": "\u0627\u0644\u0625\u062e\u0644\u0627\u0635",
    "verses_count": 4,
    "pages": [604, 604],
  },
  {
    "id": 113,
    "revelation_place": "makkah",
    "revelation_order": 20,
    "bismillah_pre": true,
    "name_simple": "Al-Falaq",
    "name_complex": "Al-Falaq",
    "name_arabic": "\u0627\u0644\u0641\u0644\u0642",
    "verses_count": 5,
    "pages": [604, 604],
  },
  {
    "id": 114,
    "revelation_place": "makkah",
    "revelation_order": 21,
    "bismillah_pre": true,
    "name_simple": "An-Nas",
    "name_complex": "An-N\u0101s",
    "name_arabic": "\u0627\u0644\u0646\u0627\u0633",
    "verses_count": 6,
    "pages": [604, 604],
  }
];
